import { Achievement } from '@/types'

export const ACHIEVEMENT_DEFINITIONS: Achievement[] = [
  {
    id: 'first-blood',
    name: 'First Blood',
    description: 'Score your first kill',
    icon: 'crosshair',
    rarity: 'common',
    maxProgress: 1,
  },
  {
    id: 'killing-spree',
    name: 'Killing Spree',
    description: 'Get 5 kills without dying',
    icon: 'fire',
    rarity: 'rare',
    maxProgress: 1,
  },
  {
    id: 'dominating',
    name: 'Dominating',
    description: 'Get 10 kills without dying',
    icon: 'lightning',
    rarity: 'epic',
    maxProgress: 1,
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Get 20 kills without dying',
    icon: 'skull',
    rarity: 'legendary',
    maxProgress: 1,
  },
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    description: 'Land 50 headshots',
    icon: 'target',
    rarity: 'rare',
    maxProgress: 50,
  },
  {
    id: 'veteran',
    name: 'Veteran',
    description: 'Complete 100 matches',
    icon: 'medal',
    rarity: 'epic',
    maxProgress: 100,
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    description: 'Win a match in under 5 minutes',
    icon: 'rocket',
    rarity: 'rare',
    maxProgress: 1,
  },
  {
    id: 'map-master',
    name: 'Map Master',
    description: 'Win on every map',
    icon: 'globe',
    rarity: 'epic',
    maxProgress: 10,
  },
  {
    id: 'perfect-game',
    name: 'Perfect Game',
    description: 'Win without dying',
    icon: 'crown',
    rarity: 'legendary',
    maxProgress: 1,
  },
  {
    id: 'comeback-kid',
    name: 'Comeback Kid',
    description: 'Win after being down by 10 kills',
    icon: 'arrow-up',
    rarity: 'epic',
    maxProgress: 1,
  },
]
