export const typography = {
  fontFamily: "'Inter', system-ui, sans-serif",
  h1: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 900,
    fontSize: '6rem',
    letterSpacing: '-0.04em',
    textTransform: 'uppercase' as const,
    lineHeight: 0.9,
  },
  h2: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 800,
    fontSize: '4rem',
    letterSpacing: '-0.03em',
    textTransform: 'uppercase' as const,
    lineHeight: 1,
  },
  h3: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 700,
    fontSize: '3rem',
    letterSpacing: '-0.02em',
    textTransform: 'uppercase' as const,
    lineHeight: 1.1,
  },
  h4: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 700,
    fontSize: '2rem',
    letterSpacing: '-0.02em',
    textTransform: 'uppercase' as const,
    lineHeight: 1.2,
  },
  h5: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 600,
    fontSize: '1.5rem',
    letterSpacing: '-0.01em',
    textTransform: 'uppercase' as const,
  },
  h6: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 600,
    fontSize: '1.25rem',
    letterSpacing: '-0.01em',
    textTransform: 'uppercase' as const,
  },
  body1: {
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '1rem',
    fontWeight: 500,
    letterSpacing: '0.01em',
  },
  body2: {
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: '0.875rem',
    fontWeight: 500,
    letterSpacing: '0.01em',
  },
  button: {
    fontFamily: "'Rajdhani', system-ui, sans-serif",
    fontWeight: 700,
    fontSize: '1.125rem',
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
  },
}
